In [ ]:
import pandas as pd 
df = pd.read_csv('Listado_Colegios.csv')

print('primeras filas del dataset')
print(df.head())

print('*******************************')
print('informacion de la estructura del dataset')
print(df.info())
print('*******************************')
print('primeras 10 filas del dataset')
print(df.head(10))
print('*******************************')
print('Ultimas 10 filas del dataset')
print(df.tail(10))
print('*******************************')
print('nombres de las columnas')
print(df.columns)
print('*******************************')
print('valores unicos')
print(df.nunique())
print('*******************************')
print('mostrar algunas filas que se encuentra duplicadas')
filas_duplicadas = df[df.duplicated()]
if not filas_duplicadas.empty:
    print(filas_duplicadas.head())
else:
    print('No hay filas duplicadas en el dataset')
print('*******************************')
print('cantidad e filas con valores nulos')
print(df.isnull().sum())
print('*******************************')
print('porcentajes de valores nulos por columna')
print(df.isnull().sum() / len(df) * 100)
print('*******************************')
columnas_con_nulos = df.columns[df.isnull().any()]
print('Columnas con valores nulos:')
print(columnas_con_nulos)
print('*******************************')
print('datos unicos en el dataset')
print(df.dtypes.value_counts())
print('*******************************')
print('cantidad de columnas por tipo de texto')
columnas_tipos_objeto= df.select_dtypes(include=['object']).columns
print(columnas_tipos_objeto)
print('*******************************')
print('ejemplo de valores en columnas de tipo caracter')
for col in columnas_tipos_objeto:
    print('ejemplo de valores en la columna {col}')
    print(df[col].dropna().unique()[:5])
print('*******************************')
columnas_numericas = df.select_dtypes(include=['int64', 'float64']).columns
print('Columnas numericas:')

for col in columnas_numericas:
    print(f'rango de datos de columnas numericas')
    #print(f'Valores unicos: {df[col].nunique()}')
    print(f'Minimo: {df[col].min()}')
    print(f'Maximo: {df[col].max()}')
    print(f'Media: {df[col].mean()}')
    #print(f'Desviacion estandar: {df[col].std()}')

primeras filas del dataset
    año secretaria                              nombreestablecimiento    zona  \
0  2016     BOGOTA  INST DE BTO TEC COMERCIAL PITAGORAS           ...  URBANA
1  2016     BOGOTA                 GIMNASIO INFANTIL FEDERICO FROEBEL  URBANA
2  2016     BOGOTA             GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA  URBANA
3  2016     BOGOTA               COLEGIO FRANCISCO PRIMERO S.S. (IED)  URBANA
4  2016     BOGOTA  COL SAN JUAN VIANETH                          ...  URBANA

           direccion             telefono                     nombre_Rector  \
0         KR 5 11 67  5665677   / 3429092                YOLANDA ARIAS CRUZ
1  CL 32 SUR 52 A 54              7100349              SANDRA MILENA MENDEZ
2     CL 134 D 47 27              6010350           CLAUDIA BOCACHICA SAENZ
3        KR 28 63 64   2126019 -- 2481271      JOSE CUSTODIO GALARZA MORENO
4    KR 2 C 3 18 SUR   2804738 -- 4714934  GLORIA ESPERANZA CHUQUIN LAISECA

    tipo_Establecimiento etnias  sector  ...  numero_de_Sedes estado  \
0  INSTITUCION EDUCATIVA    NaN     NaN  ...                1    NaN
1       CENTRO EDUCATIVO    NaN     NaN  ...                1    NaN
2  INSTITUCION EDUCATIVA    NaN     NaN  ...                1    NaN
3  INSTITUCION EDUCATIVA    NaN     NaN  ...                4    NaN
4       CENTRO EDUCATIVO    NaN     NaN  ...                1    NaN

  prestador_de_Servicio  propiedad_Planta_Fisica  resguardo  \
0       PERSONA NATURAL          PERSONA NATURAL  NO APLICA
1       PERSONA NATURAL          PERSONA NATURAL  NO APLICA
2       PERSONA NATURAL          PERSONA NATURAL  NO APLICA
3               OFICIAL                  OFICIAL  NO APLICA
4       PERSONA NATURAL          PERSONA NATURAL  NO APLICA

  matricula_Contratada calendario internado estrato_Socio_Economico  \
0                   NO          A       NaN                     NaN
1                   NO          A       NaN                     NaN
2                   NO          A       NaN                     NaN
3                   NO          A       NaN                     NaN
4                   NO          A       NaN                     NaN

                                  correo_Electronico
0                         pitagoras@pitagoras.edu.co
1                             gimfedebel@hotmail.com
2                claudialindenibocachica@hotmail.com
3                          cedalemania12@redp.edu.co
4  colegiosanjuanviateh@hotmail.com -- colegiosan...

[5 rows x 30 columns]
*******************************
informacion de la estructura del dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2404 entries, 0 to 2403
Data columns (total 30 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   año                        2404 non-null   int64
 1   secretaria                 2404 non-null   object
 2   nombreestablecimiento      2404 non-null   object
 3   zona                       2404 non-null   object
 4   direccion                  2404 non-null   object
 5   telefono                   2342 non-null   object
 6   nombre_Rector              2404 non-null   object
 7   tipo_Establecimiento       2404 non-null   object
 8   etnias                     71 non-null     object
 9   sector                     0 non-null      float64
 10  genero                     0 non-null      float64
 11  niveles                    2388 non-null   object
 12  jornadas                   2391 non-null   object
 13  caracter                   0 non-null      float64
 14  especialidad               1294 non-null   object
 15  grados                     2388 non-null   object
 16  modelos_Educativos         2366 non-null   object
 17  capacidades_Excepcionales  10 non-null     object
 18  discapacidades             514 non-null    object
 19  idiomas                    943 non-null    object
 20  numero_de_Sedes            2404 non-null   int64
 21  estado                     0 non-null      float64
 22  prestador_de_Servicio      2404 non-null   object
 23  propiedad_Planta_Fisica    2404 non-null   object
 24  resguardo                  2404 non-null   object
 25  matricula_Contratada       2404 non-null   object
 26  calendario                 2404 non-null   object
 27  internado                  0 non-null      float64
 28  estrato_Socio_Economico    4 non-null      object
 29  correo_Electronico         1976 non-null   object
dtypes: float64(5), int64(2), object(23)
memory usage: 563.6+ KB
None
*******************************
primeras 10 filas del dataset
    año secretaria                              nombreestablecimiento    zona  \
0  2016     BOGOTA  INST DE BTO TEC COMERCIAL PITAGORAS           ...  URBANA
1  2016     BOGOTA                 GIMNASIO INFANTIL FEDERICO FROEBEL  URBANA
2  2016     BOGOTA             GIMNASIO INFANTIL LOS NIÑOS DEL MAÑANA  URBANA
3  2016     BOGOTA               COLEGIO FRANCISCO PRIMERO S.S. (IED)  URBANA
4  2016     BOGOTA  COL SAN JUAN VIANETH                          ...  URBANA
5  2016     BOGOTA  COL SAN PATRICIO                              ...  URBANA
6  2016     BOGOTA  COL CRISTIANO FUENTE DE VIDA                  ...  URBANA
7  2016     BOGOTA  LIC PARROQ SAN JOSE                           ...  URBANA
8  2016     BOGOTA  LIC ESTRELLITA ESTUDIANTIL                    ...  URBANA
9  2016     BOGOTA                               COL LUIGI PIRANDELLO  URBANA

              direccion             telefono  \
0            KR 5 11 67  5665677   / 3429092
1     CL 32 SUR 52 A 54              7100349
2        CL 134 D 47 27              6010350
3           KR 28 63 64   2126019 -- 2481271
4       KR 2 C 3 18 SUR   2804738 -- 4714934
5          KR 80 137 02   6838640 -- 6815357
6  CL 89 A BIS B 113 45              4316805
7   TV 13 H 45 F 33 SUR              7607585
8           KR 64 64 64              2310592
9        KR 113 74 B 06   4424545 -- 2286068

                      nombre_Rector   tipo_Establecimiento etnias  sector  \
0                YOLANDA ARIAS CRUZ  INSTITUCION EDUCATIVA    NaN     NaN
1              SANDRA MILENA MENDEZ       CENTRO EDUCATIVO    NaN     NaN
2           CLAUDIA BOCACHICA SAENZ  INSTITUCION EDUCATIVA    NaN     NaN
3      JOSE CUSTODIO GALARZA MORENO  INSTITUCION EDUCATIVA    NaN     NaN
4  GLORIA ESPERANZA CHUQUIN LAISECA       CENTRO EDUCATIVO    NaN     NaN
5     PAULINA ENCINALES DE SANJINES  INSTITUCION EDUCATIVA    NaN     NaN
6           SANDRA PATRICIA ESPITIA       CENTRO EDUCATIVO    NaN     NaN
7             ANDRES PEREZ LIZARAZO  INSTITUCION EDUCATIVA    NaN     NaN
8       PATRICIA CASTIBLANCO TORRES       CENTRO EDUCATIVO    NaN     NaN
9      JORGE HERNAN NARANJO PUERTAS  INSTITUCION EDUCATIVA    NaN     NaN

   ...  numero_de_Sedes estado prestador_de_Servicio  propiedad_Planta_Fisica  \
0  ...                1    NaN       PERSONA NATURAL          PERSONA NATURAL
1  ...                1    NaN       PERSONA NATURAL          PERSONA NATURAL
2  ...                1    NaN       PERSONA NATURAL          PERSONA NATURAL
3  ...                4    NaN               OFICIAL                  OFICIAL
4  ...                1    NaN       PERSONA NATURAL          PERSONA NATURAL
5  ...                1    NaN       PERSONA NATURAL          PERSONA NATURAL
6  ...                1    NaN       PERSONA NATURAL          PERSONA NATURAL
7  ...                1    NaN       PERSONA NATURAL          PERSONA NATURAL
8  ...                1    NaN       PERSONA NATURAL          PERSONA NATURAL
9  ...                1    NaN       PERSONA NATURAL          PERSONA NATURAL

   resguardo matricula_Contratada calendario internado  \
0  NO APLICA                   NO          A       NaN
1  NO APLICA                   NO          A       NaN
2  NO APLICA                   NO          A       NaN
3  NO APLICA                   NO          A       NaN
4  NO APLICA                   NO          A       NaN
5  NO APLICA                   NO          A       NaN
6  NO APLICA                   NO          A       NaN
7  NO APLICA                   NO          A       NaN
8  NO APLICA                   NO          A       NaN
9  NO APLICA                   NO          A       NaN

  estrato_Socio_Economico                                 correo_Electronico
0                     NaN                         pitagoras@pitagoras.edu.co
1                     NaN                             gimfedebel@hotmail.com
2                     NaN                claudialindenibocachica@hotmail.com
3                     NaN                          cedalemania12@redp.edu.co
4                     NaN  colegiosanjuanviateh@hotmail.com -- colegiosan...
5                     NaN                 correo@colegiodesanpatricio.edu.co
6                     NaN  fuentedevida9@latinmail.com                   ...
7                     NaN                                 lpsj2003@yahoo.com
8                     NaN  lee5815@hotmail.com   estrellitaestudiantil@ho...
9                     NaN  clp2013academico@gmail.com -- clp.secretaria@g...

[10 rows x 30 columns]
*******************************
Ultimas 10 filas del dataset
       año secretaria                              nombreestablecimiento  \
2394  2016     BOGOTA                           COL INTEGRAL SOCORRO III
2395  2016     BOGOTA  LIC PEDAG CIENCIA Y CULTURA                   ...
2396  2016     BOGOTA  LIC PARROQ SAN GREGORIO MAGNO                 ...
2397  2016     BOGOTA                      COLEGIO BRASILIA - BOSA (IED)
2398  2016     BOGOTA                       COLEGIO ANTONIO BARAYA (IED)
2399  2016     BOGOTA                       COLEGIO SAN JOSE DE CALASANZ
2400  2016     BOGOTA                        COL NUEVO REINO DE TURINGIA
2401  2016     BOGOTA  LIC  INF GOOFY                                ...
2402  2016     BOGOTA  LIC APRENDO CON MIS AMIGOS                    ...
2403  2016     BOGOTA  JARD INF EL ROSAL DE MI INFANCIA              ...

        zona              direccion                              telefono  \
2394  URBANA  TR. 16F NO.49B-35 SUR                               7677912
2395  URBANA     CR. 114 NO.152B-63                               5366698
2396  URBANA             KR 29 9 47                               2477407
2397  URBANA    CL 52 A SUR 87 D 45                               7831779
2398  URBANA      CL 27 SUR 22 A 02                     2392403 / 3668171
2399  URBANA         CL 129 88 B 35        6854492 -- 6854495 -- 6803549
2400  URBANA      KR 103 B 152 C 34                               6830915
2401  URBANA    CL 65 F SUR 78 C 32  7761739 / 7762538 / 7753157 /8045802
2402  URBANA        CR. 94 NO.29-30                               2671099
2403  URBANA   TR. 56A NO.45-18 SUR                               7242172

                          nombre_Rector   tipo_Establecimiento etnias  sector  \
2394        GLORIA MARINA SILVA FANDIÑO       CENTRO EDUCATIVO    NaN     NaN
2395            CLARA MARIA DIAZ ROMERO       CENTRO EDUCATIVO    NaN     NaN
2396                   RAFAEL HERNANDEZ  INSTITUCION EDUCATIVA    NaN     NaN
2397             NANCY FERNANDEZ RINCON  INSTITUCION EDUCATIVA    NaN     NaN
2398     MARTHA ISABEL BOGOTA TRANCHITA  INSTITUCION EDUCATIVA    NaN     NaN
2399              GLADIS CUÉLLAR IBAÑEZ  INSTITUCION EDUCATIVA    NaN     NaN
2400        RUTH CECILIA CORREA FAJARDO       CENTRO EDUCATIVO    NaN     NaN
2401  SANDRA PATRICIA SANTAMARIA OVALLE       CENTRO EDUCATIVO    NaN     NaN
2402    YANNETH CONSUELO BOLIVAR GAITAN       CENTRO EDUCATIVO    NaN     NaN
2403                    ADALGIZA LADINO       CENTRO EDUCATIVO    NaN     NaN

      ...  numero_de_Sedes estado prestador_de_Servicio  \
2394  ...                1    NaN       PERSONA NATURAL
2395  ...                1    NaN       PERSONA NATURAL
2396  ...                1    NaN   COMUNIDAD RELIGIOSA
2397  ...                3    NaN               OFICIAL
2398  ...                2    NaN               OFICIAL
2399  ...                1    NaN   COMUNIDAD RELIGIOSA
2400  ...                1    NaN       PERSONA NATURAL
2401  ...                1    NaN       PERSONA NATURAL
2402  ...                1    NaN       PERSONA NATURAL
2403  ...                1    NaN       PERSONA NATURAL

      propiedad_Planta_Fisica  resguardo matricula_Contratada calendario  \
2394          PERSONA NATURAL  NO APLICA                   NO          A
2395          PERSONA NATURAL  NO APLICA                   NO          A
2396      COMUNIDAD RELIGIOSA  NO APLICA                   NO          A
2397                  OFICIAL  NO APLICA                   NO          A
2398                  OFICIAL  NO APLICA                   NO          A
2399      COMUNIDAD RELIGIOSA  NO APLICA                   NO          A
2400          PERSONA NATURAL  NO APLICA                   NO          A
2401          PERSONA NATURAL  NO APLICA                   NO          A
2402          PERSONA NATURAL  NO APLICA                   NO          A
2403          PERSONA NATURAL  NO APLICA                   NO          A

     internado estrato_Socio_Economico  \
2394       NaN                     NaN
2395       NaN                     NaN
2396       NaN                     NaN
2397       NaN                     NaN
2398       NaN                     NaN
2399       NaN                     NaN
2400       NaN                     NaN
2401       NaN                     NaN
2402       NaN                     NaN
2403       NaN                     NaN

                                     correo_Electronico
2394                                                NaN
2395                                                NaN
2396                                  lpsgm@tutopia.com
2397                      cedbrasiliabosa7@gmail.com.co
2398                     cedantoniobaraya18@redp.edu.co
2399                                  csjcsuba@yahoo.es
2400  jibnuevoreinodeturingia@hotmail.com - ruth_cec...
2401  pattysantaco@yahoo.com   directoragoofy@gmail....
2402                                                NaN
2403  adalgizaladino@hotmail.com                    ...

[10 rows x 30 columns]
*******************************
nombres de las columnas
Index(['año', 'secretaria', 'nombreestablecimiento', 'zona', 'direccion',
       'telefono', 'nombre_Rector', 'tipo_Establecimiento', 'etnias', 'sector',
       'genero', 'niveles', 'jornadas', 'caracter', 'especialidad', 'grados',
       'modelos_Educativos', 'capacidades_Excepcionales', 'discapacidades',
       'idiomas', 'numero_de_Sedes', 'estado', 'prestador_de_Servicio',
       'propiedad_Planta_Fisica', 'resguardo', 'matricula_Contratada',
       'calendario', 'internado', 'estrato_Socio_Economico',
       'correo_Electronico'],
      dtype='object')
*******************************
valores unicos
año                             1
secretaria                      1
nombreestablecimiento        2387
zona                            3
direccion                    2377
telefono                     2328
nombre_Rector                2354
tipo_Establecimiento            2
etnias                         11
sector                          0
genero                          0
niveles                        18
jornadas                       41
caracter                        0
especialidad                   21
grados                        180
modelos_Educativos             32
capacidades_Excepcionales       4
discapacidades                124
idiomas                         7
numero_de_Sedes                 7
estado                          0
prestador_de_Servicio          10
propiedad_Planta_Fisica        10
resguardo                       2
matricula_Contratada            2
calendario                      3
internado                       0
estrato_Socio_Economico         2
correo_Electronico           1961
dtype: int64
*******************************
mostrar algunas filas que se encuentra duplicadas
No hay filas duplicadas en el dataset
*******************************
cantidad e filas con valores nulos
año                             0
secretaria                      0
nombreestablecimiento           0
zona                            0
direccion                       0
telefono                       62
nombre_Rector                   0
tipo_Establecimiento            0
etnias                       2333
sector                       2404
genero                       2404
niveles                        16
jornadas                       13
caracter                     2404
especialidad                 1110
grados                         16
modelos_Educativos             38
capacidades_Excepcionales    2394
discapacidades               1890
idiomas                      1461
numero_de_Sedes                 0
estado                       2404
prestador_de_Servicio           0
propiedad_Planta_Fisica         0
resguardo                       0
matricula_Contratada            0
calendario                      0
internado                    2404
estrato_Socio_Economico      2400
correo_Electronico            428
dtype: int64
*******************************
porcentajes de valores nulos por columna
año                            0.000000
secretaria                     0.000000
nombreestablecimiento          0.000000
zona                           0.000000
direccion                      0.000000
telefono                       2.579035
nombre_Rector                  0.000000
tipo_Establecimiento           0.000000
etnias                        97.046589
sector                       100.000000
genero                       100.000000
niveles                        0.665557
jornadas                       0.540765
caracter                     100.000000
especialidad                  46.173045
grados                         0.665557
modelos_Educativos             1.580699
capacidades_Excepcionales     99.584027
discapacidades                78.618968
idiomas                       60.773710
numero_de_Sedes                0.000000
estado                       100.000000
prestador_de_Servicio          0.000000
propiedad_Planta_Fisica        0.000000
resguardo                      0.000000
matricula_Contratada           0.000000
calendario                     0.000000
internado                    100.000000
estrato_Socio_Economico       99.833611
correo_Electronico            17.803661
dtype: float64